// Appendix A generated from a contract document (RN §3: the appendix is
// generated from the engine's schema and transition tables; Plan M73; SEAM.md
// §94). The text follows the document it is given and nothing else: the same
// document gives the same text, and D1's hand-written appendix is not an
// input. Enumerations are written in D1 A.2's form, one line each, with the
// values in the document's order.

type Obj = Record<string, unknown>;
const isObj = (v: unknown): v is Obj => typeof v === 'object' && v !== null && !Array.isArray(v);
const list = (v: unknown): unknown[] => (Array.isArray(v) ? v : []);
const text = (v: unknown): string => (typeof v === 'string' ? v : JSON.stringify(v));

export function generateAppendix(doc: unknown): string {
  const d = isObj(doc) ? doc : {};
  const out: string[] = [];
  out.push('# Appendix A, generated from the executable contract');
  out.push('');
  out.push('Generated by `surety contract appendix` from the engine\'s contract (`packages/engine/api/schema.json`). Do not edit by hand: change the engine and generate it again.');
  out.push('');

  out.push('## A.2 Enumerations');
  out.push('');
  for (const [name, values] of Object.entries(isObj(d.enums) ? d.enums : {})) out.push(`- **${name}:** ${list(values).map(text).join(', ')}.`);
  out.push('');

  out.push('## A.3 Tables and fields');
  out.push('');
  out.push('Notation: `*` required; `=Enum` one of A.2; `→table` a foreign key.');
  out.push('');
  for (const [table, spec] of Object.entries(isObj(d.tables) ? d.tables : {})) {
    const fields = isObj(spec) && isObj(spec.fields) ? spec.fields : {};
    const parts = Object.entries(fields).map(([field, f]) => {
      const s = isObj(f) ? f : {};
      return `\`${field}${s.required === true ? '*' : ''}${typeof s.enum === 'string' ? ` =${s.enum}` : ''}${typeof s.references === 'string' ? ` →${s.references}` : ''}\``;
    });
    out.push(`- **${table}:** ${parts.join(', ')}.`);
  }
  out.push('');

  out.push('## A.5 Transitions');
  out.push('');
  const work = isObj(d.work_items) ? d.work_items : {};
  out.push('### Work items');
  out.push('');
  for (const [kind, spec] of Object.entries(isObj(work.kinds) ? work.kinds : {})) {
    const s = isObj(spec) ? spec : {};
    out.push(`- \`${kind}\`${s.m1 === true ? '' : ' (not dispatched in M1)'}: ${list(s.path).map(text).join(' → ')}`);
  }
  out.push('');
  out.push('Common transitions, applied to a kind only from the statuses it can reach:');
  out.push('');
  for (const [name, t] of Object.entries(isObj(work.templates) ? work.templates : {})) {
    const s = isObj(t) ? t : {};
    const to = s.to === null ? 'the stored continuation' : text(s.to);
    out.push(`- \`${name}\`: ${list(s.from).map(text).join(', ')} → ${to}${typeof s.only_kinds_with === 'string' ? ` (kinds whose path has ${s.only_kinds_with})` : ''}`);
  }
  out.push('');
  out.push(`Statuses that own a run: ${list(work.run_owning).map(text).join(', ')}. Continuations: ${list(work.continuations).map(text).join(', ')}. Terminal: ${list(work.terminal).map(text).join(', ')}.`);
  out.push('');
  for (const [name, chains] of Object.entries(isObj(d.transitions) ? d.transitions : {})) {
    out.push(`### ${name}`);
    out.push('');
    for (const chain of list(chains)) out.push(`- ${list(chain).map(text).join(' → ')}`);
    out.push('');
  }

  out.push('## A.6 Events');
  out.push('');
  for (const [type, spec] of Object.entries(isObj(d.events) ? d.events : {})) {
    const s = isObj(spec) ? spec : {};
    out.push(`- \`${type}\`: ${s.reserved === true ? 'reserved' : `emitted by ${text(s.owner)}`}`);
  }
  out.push('');

  out.push('## A.8 Decision kinds');
  out.push('');
  for (const [kind, spec] of Object.entries(isObj(d.decisions) ? d.decisions : {})) {
    const s = isObj(spec) ? spec : {};
    out.push(s.enabled === true ? `- \`${kind}\`: enabled; manifest ${list(s.manifest).map(text).join(', ')}` : `- \`${kind}\`: not enabled in M1`);
  }
  out.push('');

  out.push('## A.9 Configuration');
  out.push('');
  const config = isObj(d.config) ? d.config : {};
  for (const scope of ['engine', 'project']) {
    out.push(`### ${scope}`);
    out.push('');
    for (const [key, spec] of Object.entries(isObj(config[scope]) ? (config[scope] as Obj) : {})) {
      const s = isObj(spec) ? spec : {};
      const range = typeof s.min === 'number' && typeof s.max === 'number' ? `, ${s.min} to ${s.max}` : s.fixed === true ? ', fixed' : '';
      out.push(`- \`${key}\`: default ${text(s.default)}${range}`);
    }
    out.push('');
  }
  return out.join('\n');
}
