// The event types the engine emits (D1 §12.1, A.6), each with what emits it:
// the transition module that writes it. The set is closed: Tx.emit takes no
// other type, and the executable contract (contract/) states this table.

export const EVENT_OWNERS = {
  'engine.started': 'store/transitions/engine.ts',
  'engine.mode_changed': 'store/transitions/engine.ts',
  'engine.tick': 'store/transitions/engine.ts',
  'engine.quarantine': 'store/transitions/runs.ts',
  'api.act': 'store/transitions/audit.ts',
  'project.created': 'store/transitions/project.ts',
  'project.registered': 'store/transitions/finalize.ts',
  'project.paused': 'store/transitions/project.ts',
  'project.resumed': 'store/transitions/project.ts',
  'project.rebound': 'store/transitions/project.ts',
  'work.created': 'store/transitions/work.ts',
  'work.claimed': 'store/transitions/work.ts',
  'work.advanced': 'store/transitions/work.ts',
  'work.integrated': 'store/transitions/work.ts',
  'work.complete': 'store/transitions/work.ts',
  'work.held': 'store/transitions/work.ts',
  'work.resumed': 'store/transitions/work.ts',
  'work.parked': 'store/transitions/work.ts',
  'work.cancelled': 'store/transitions/work.ts',
  'run.created': 'store/transitions/runs.ts',
  'run.claimed': 'store/transitions/runs.ts',
  'run.started': 'store/transitions/runs.ts',
  'run.heartbeat': 'store/transitions/runs.ts',
  'run.validating': 'store/transitions/runs.ts',
  'run.finalizing': 'store/transitions/runs.ts',
  'run.ended': 'store/transitions/runs.ts',
  'run.quarantined': 'store/transitions/runs.ts',
  'domain.terminated': 'store/transitions/runs.ts',
  'domain.quarantined': 'store/transitions/runs.ts',
  'decision.raised': 'store/transitions/decisions.ts',
  'decision.answered': 'store/transitions/decisions.ts',
  'decision.consumed': 'store/transitions/decisions.ts',
  'decision.invalidated': 'store/transitions/decisions.ts',
  'operation.intended': 'store/transitions/journal.ts',
  'operation.attempt_started': 'store/transitions/journal.ts',
  'operation.succeeded': 'store/transitions/journal.ts',
  'operation.failed': 'store/transitions/journal.ts',
  'operation.partial': 'store/transitions/journal.ts',
  'operation.ambiguous': 'store/transitions/journal.ts',
  'operation.finalized': 'store/transitions/journal.ts',
  'revision.recorded': 'store/transitions/repo.ts',
  'candidate.nominated': 'store/transitions/finalize.ts',
  'repo.out_of_band': 'store/transitions/repo.ts',
  'repo.reconciled': 'store/transitions/finalize.ts, store/transitions/intents.ts, store/transitions/queue.ts, store/transitions/repo.ts',
  'policy.changed': 'store/transitions/finalize.ts',
  'git.journal_intended': 'store/transitions/journal.ts',
  'git.journal_applied': 'store/transitions/journal.ts',
  'git.journal_confirmed': 'store/transitions/journal.ts',
  'git.journal_ambiguous': 'store/transitions/journal.ts',
  'git.journal_finalized': 'store/transitions/journal.ts',
  'invocation.receipt': 'store/transitions/runs.ts',
  'invocation.status': 'store/transitions/runs.ts',
  'invocation.usage': 'store/transitions/runs.ts',
  'ledger.row': 'store/transitions/ledger.ts',
  'ledger.correction': 'store/transitions/ledger.ts',
  'record.written': 'store/transitions/records.ts',
  'record.expired': 'store/transitions/records.ts',
  'record.secret_found': 'store/transitions/records.ts',
  'record.missing': 'store/transitions/records.ts',
  'run.proposal_captured': 'store/transitions/accept.ts',
  'decision.escalated': 'store/transitions/queue.ts',
  'protected.proposed': 'store/transitions/protected.ts',
  'protected.classified': 'store/transitions/protected.ts',
  'protected.approved': 'store/transitions/protected.ts',
  'protected.rejected': 'store/transitions/queue.ts',
  'protected.applied': 'store/transitions/protected.ts',
  'protected.unauthorized_detected': 'store/transitions/gates.ts',
  'check.result': 'store/transitions/baseline.ts',
  'gate.scope_built': 'store/transitions/gates.ts',
  'gate.evaluated': 'store/transitions/gates.ts',
  'authorization.issued': 'store/transitions/gates.ts',
  'authorization.superseded': 'store/transitions/gates.ts',
  'finding.raised': 'store/transitions/findings.ts',
  'finding.severity_changed': 'store/transitions/queue.ts',
  'finding.dispositioned': 'store/transitions/queue.ts',
  'finding.resolved': 'store/transitions/gates.ts',
  'finding.reopened': 'store/transitions/protected.ts',
  'assessment.proposed': 'store/transitions/findings.ts',
  'assessment.assessed': 'store/transitions/findings.ts',
  'assessment.approved': 'store/transitions/queue.ts',
  'assessment.rejected': 'store/transitions/findings.ts, store/transitions/queue.ts',
  'signoff.recorded': 'store/transitions/findings.ts',
  'intent.recorded': 'store/transitions/queue.ts',
  'intent.executing': 'store/transitions/intents.ts, store/transitions/protected.ts',
  'intent.done': 'store/transitions/protected.ts',
  'intent.invalidated': 'store/transitions/queue.ts',
  'notification.queued': 'store/transitions/queue.ts',
  'notification.sending': 'store/transitions/notify.ts',
  'notification.delivered': 'store/transitions/notify.ts',
  'notification.failed': 'store/transitions/notify.ts',
  'notification.unknown': 'store/transitions/notify.ts',
  'environment.observed': 'store/transitions/environments.ts',
  'engine.backup': 'store/transitions/engine.ts',
  // D2 A.5, the trust table's part. The egress and secret events join with
  // the sandbox lane's later slices, which emit them.
  'host.qualified': 'store/transitions/trust.ts',
  'host.qualification_lapsed': 'store/transitions/trust.ts',
  'qualification.proposed': 'store/transitions/trust.ts',
  'qualification.authorized': 'store/transitions/trust.ts',
  'qualification.finished': 'store/transitions/trust.ts',
  'trust.proposed': 'store/transitions/trust.ts',
  'trust.activated': 'store/transitions/trust.ts',
  'trust.revoked': 'store/transitions/trust.ts',
  // D2 A.5, the boundary's part (M2 slice 11).
  'domain.placed': 'store/transitions/boundary.ts',
  'domain.launch_authorized': 'store/transitions/boundary.ts',
  'domain.launch_closed': 'store/transitions/boundary.ts',
  'run.lease_regranted': 'store/transitions/boundary.ts',
} as const;

export type EventType = keyof typeof EVENT_OWNERS;

export const EVENT_TYPES = Object.keys(EVENT_OWNERS) as EventType[];
